# Generated by Django 5.0.4 on 2024-05-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dealsitem_specialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
