# Generated by Django 4.2.11 on 2024-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='Food',
            field=models.CharField(default="Nick's GOATed Burger", max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='Type',
            field=models.CharField(default='Entree', max_length=255),
        ),
    ]
