# Generated by Django 5.0.4 on 2024-04-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_food_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
    ]
